import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import { getServerAuthSession } from "~/server/auth";
import Profile from "./_components/profile";

export const metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await getServerAuthSession();
	return (
		<html lang="en" className={`${GeistSans.variable}`}>
			<body>
				{session && (
					<Profile session={session} />
				)}
				<TRPCReactProvider>{children}</TRPCReactProvider>
			</body>
		</html>
	);
}
