import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import { getServerAuthSession } from "~/server/auth";
import Profile from "./_components/profile";
import { Inter as FontSans } from "next/font/google"
import { cn } from "~/lib/utils";

export const metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};
const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
})

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await getServerAuthSession();
	return (
		<html lang="en" className={`${GeistSans.variable}`}>
			<body
				className={cn(
					"min-h-screen bg-background font-sans antialiased",
					fontSans.variable
				)}
			>
				{session && (
					<Profile session={session} />
				)}
				<TRPCReactProvider>{children}</TRPCReactProvider>
			</body>
		</html>
	);
}
